--<ScriptOptions statementTerminator=";"/>

CREATE DATABASE "DNNK17"
	BUFFERPOOL BP1
	INDEXBP BP2
	STOGROUP GNNK17
	CCSID EBCDIC;

CREATE  TABLESPACE "SNK17010"
	IN DNNK17
	USING STOGROUP GNNK17
	  PRIQTY -1
	  SECQTY -1
	PCTFREE 10
	DSSIZE 4 G
	MAXPARTITIONS 50
	SEGSIZE 32
	BUFFERPOOL BP1
	CCSID EBCDIC
	CLOSE NO
	COMPRESS YES
	LOCKMAX SYSTEM
	LOCKSIZE ANY
	MAXROWS 255;

CREATE  TABLESPACE "SNK17020"
	IN DNNK17
	USING STOGROUP GNNK17
	  PRIQTY -1
	  SECQTY -1
	PCTFREE 10
	DSSIZE 4 G
	MAXPARTITIONS 50
	SEGSIZE 32
	BUFFERPOOL BP1
	CCSID EBCDIC
	CLOSE NO
	COMPRESS YES
	LOCKMAX SYSTEM
	LOCKSIZE ROW
	MAXROWS 255;

CREATE  TABLESPACE "SNK17031"
	IN DNNK17
	USING STOGROUP GNNK17
	  PRIQTY -1
	  SECQTY -1
	DSSIZE 4 G
	MAXPARTITIONS 50
	SEGSIZE 32
	BUFFERPOOL BP1
	CCSID EBCDIC
	CLOSE NO
	COMPRESS YES
	LOCKMAX SYSTEM
	LOCKSIZE ANY
	MAXROWS 255;

