--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "NK"."TNK17010" (
		"SEQ_NR" INTEGER NOT NULL, 
		"NM" VARCHAR(20) FOR SBCS DATA NOT NULL, 
		"CRE_TS" TIMESTAMP NOT NULL, 
		"CRE_USR_NR" VARCHAR(8) FOR SBCS DATA NOT NULL, 
		"UPD_TS" TIMESTAMP NOT NULL, 
		"UPD_USR_NR" VARCHAR(8) FOR SBCS DATA NOT NULL, 
		"DSC" VARCHAR(50) FOR SBCS DATA NOT NULL
	)
	IN "DNNK17"."SNK17010"
	PARTITION BY SIZE EVERY 4 G 
	AUDIT NONE
	DATA CAPTURE NONE 
	CCSID EBCDIC;

CREATE TABLE "NK"."TNK17020" (
		"SEQ_NR" INTEGER NOT NULL, 
		"STA_CD" CHAR(20) FOR SBCS DATA NOT NULL, 
		"CRE_TS" TIMESTAMP NOT NULL, 
		"CRE_USR_NR" VARCHAR(8) FOR SBCS DATA NOT NULL, 
		"UPD_TS" TIMESTAMP NOT NULL, 
		"UPD_USR_NR" VARCHAR(8) FOR SBCS DATA NOT NULL, 
		"IFAC_APPL_SEQ_NR" INTEGER NOT NULL, 
		"ORIG_SYM" VARCHAR(20) FOR SBCS DATA NOT NULL, 
		"RCD_TYP" VARCHAR(20) FOR SBCS DATA NOT NULL, 
		"STA_DSC" VARCHAR(250) FOR SBCS DATA WITH DEFAULT NULL, 
		"MSG_HDR" VARCHAR(3600) FOR SBCS DATA NOT NULL WITH DEFAULT
	)
	IN "DNNK17"."SNK17020"
	PARTITION BY SIZE EVERY 4 G 
	AUDIT NONE
	DATA CAPTURE NONE 
	CCSID EBCDIC;

CREATE TABLE "NK"."TNK17030" (
		"SWLW_OUTR_IFAC_SEQ_NR" INTEGER NOT NULL, 
		"SNR" SMALLINT NOT NULL, 
		"RCD_TXT" CLOB(10485760) FOR SBCS DATA NOT NULL
	)
	IN "DNNK17"."SNK17031"
	PARTITION BY SIZE EVERY 4 G 
	AUDIT NONE
	DATA CAPTURE NONE 
	CCSID EBCDIC;

CREATE INDEX "NK"."XNK1702B"
	ON "NK"."TNK17020"
	("IFAC_APPL_SEQ_NR"		ASC)
	NOT CLUSTER
	USING STOGROUP GNNK17X
	  PRIQTY -1
	  SECQTY -1
	BUFFERPOOL BP2     
	CLOSE NO
	PIECESIZE 4194304 K;

CREATE INDEX "NK"."XNK1702C"
	ON "NK"."TNK17020"
	("ORIG_SYM"		ASC, 
	  "STA_CD"		ASC, 
	  "SEQ_NR"		ASC)
	NOT CLUSTER
	PADDED
	USING STOGROUP GNNK17X
	  PRIQTY -1
	  SECQTY -1
	BUFFERPOOL BP2     
	CLOSE NO
	PIECESIZE 4194304 K;

CREATE INDEX "NK"."XNK1702D"
	ON "NK"."TNK17020"
	("STA_CD"		ASC, 
	  "CRE_TS"		ASC)
	NOT CLUSTER
	USING STOGROUP GNNK17X
	  PRIQTY -1
	  SECQTY -1
	BUFFERPOOL BP2     
	CLOSE NO
	PIECESIZE 4194304 K;

CREATE UNIQUE INDEX "NK"."CNK1702A"
	ON "NK"."TNK17020"
	("SEQ_NR");

CREATE UNIQUE INDEX "NK"."SEQ_NR"
	ON "NK"."TNK17010"
	("SEQ_NR");

CREATE UNIQUE INDEX "NK"."TNK17030_PK"
	ON "NK"."TNK17030"
	("SWLW_OUTR_IFAC_SEQ_NR", 
	 "SNR");

CREATE UNIQUE INDEX "NK"."XNK1701B"
	ON "NK"."TNK17010"
	("NM"		ASC)
	NOT CLUSTER
	PADDED
	USING STOGROUP GNNK17X
	  PRIQTY -1
	  SECQTY -1
	BUFFERPOOL BP2     
	CLOSE NO
	PIECESIZE 4194304 K;

ALTER TABLE "NK"."TNK17010" ADD CONSTRAINT "SEQ_NR" PRIMARY KEY
	("SEQ_NR");

ALTER TABLE "NK"."TNK17020" ADD CONSTRAINT "CNK1702A" PRIMARY KEY
	("SEQ_NR");

ALTER TABLE "NK"."TNK17030" ADD CONSTRAINT "TNK17030_PK" PRIMARY KEY
	("SWLW_OUTR_IFAC_SEQ_NR", 
	 "SNR");

ALTER TABLE "NK"."TNK17020" ADD CONSTRAINT "LNK17021" FOREIGN KEY
	("IFAC_APPL_SEQ_NR")
	REFERENCES "NK"."TNK17010"
	("SEQ_NR")
	ON DELETE RESTRICT;

ALTER TABLE "NK"."TNK17030" ADD CONSTRAINT "LNK17032" FOREIGN KEY
	("SWLW_OUTR_IFAC_SEQ_NR")
	REFERENCES "NK"."TNK17020"
	("SEQ_NR")
	ON DELETE CASCADE;

GRANT ALTER ON TABLE "NK"."TNK17010" TO "NK" WITH GRANT OPTION;

GRANT ALTER ON TABLE "NK"."TNK17020" TO "NK" WITH GRANT OPTION;

GRANT ALTER ON TABLE "NK"."TNK17030" TO "NK" WITH GRANT OPTION;

GRANT DELETE ON TABLE "NK"."TNK17010" TO "NK" WITH GRANT OPTION;

GRANT DELETE ON TABLE "NK"."TNK17020" TO "NK" WITH GRANT OPTION;

GRANT DELETE ON TABLE "NK"."TNK17030" TO "NK" WITH GRANT OPTION;

GRANT INDEX ON TABLE "NK"."TNK17010" TO "NK" WITH GRANT OPTION;

GRANT INDEX ON TABLE "NK"."TNK17020" TO "NK" WITH GRANT OPTION;

GRANT INDEX ON TABLE "NK"."TNK17030" TO "NK" WITH GRANT OPTION;

GRANT INSERT ON TABLE "NK"."TNK17010" TO "NK" WITH GRANT OPTION;

GRANT INSERT ON TABLE "NK"."TNK17020" TO "NK" WITH GRANT OPTION;

GRANT INSERT ON TABLE "NK"."TNK17030" TO "NK" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "NK"."TNK17010" TO "NK" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "NK"."TNK17020" TO "NK" WITH GRANT OPTION;

GRANT REFERENCES ON TABLE "NK"."TNK17030" TO "NK" WITH GRANT OPTION;

GRANT SELECT ON TABLE "NK"."TNK17010" TO "NK" WITH GRANT OPTION;

GRANT SELECT ON TABLE "NK"."TNK17020" TO "NK" WITH GRANT OPTION;

GRANT SELECT ON TABLE "NK"."TNK17030" TO "NK" WITH GRANT OPTION;

GRANT TRIGGER ON TABLE "NK"."TNK17010" TO "NK" WITH GRANT OPTION;

GRANT TRIGGER ON TABLE "NK"."TNK17020" TO "NK" WITH GRANT OPTION;

GRANT TRIGGER ON TABLE "NK"."TNK17030" TO "NK" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "NK"."TNK17010" TO "NK" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "NK"."TNK17020" TO "NK" WITH GRANT OPTION;

GRANT UPDATE ON TABLE "NK"."TNK17030" TO "NK" WITH GRANT OPTION;

LABEL ON COLUMN "NK"."TNK17020"."CRE_TS" IS
'CRE_TS';

LABEL ON COLUMN "NK"."TNK17020"."CRE_USR_NR" IS
'CRE_USR_NR';

LABEL ON COLUMN "NK"."TNK17020"."IFAC_APPL_SEQ_NR" IS
'IFAC_APPL_SEQ_NR';

LABEL ON COLUMN "NK"."TNK17020"."MSG_HDR" IS
'MSG_HDR';

LABEL ON COLUMN "NK"."TNK17020"."ORIG_SYM" IS
'ORIG_SYM';

LABEL ON COLUMN "NK"."TNK17020"."RCD_TYP" IS
'RCD_TYP';

LABEL ON COLUMN "NK"."TNK17020"."SEQ_NR" IS
'SEQ_NR';

LABEL ON COLUMN "NK"."TNK17020"."STA_CD" IS
'STA_CD';

LABEL ON COLUMN "NK"."TNK17020"."STA_DSC" IS
'STA_DSC';

LABEL ON COLUMN "NK"."TNK17020"."UPD_TS" IS
'UPD_TS';

LABEL ON COLUMN "NK"."TNK17020"."UPD_USR_NR" IS
'UPD_USR_NR';

LABEL ON TABLE "NK"."TNK17010" IS
'IFAC_APPL';

LABEL ON TABLE "NK"."TNK17020" IS
'SWLW_OUTR_IFAC';

LABEL ON TABLE "NK"."TNK17030" IS
'SWLW_OUTR_IFAC_TXT';

