--<ScriptOptions statementTerminator=";"/>

CREATE LOB  TABLESPACE "SNK1703L"
	IN DNNK17
	USING STOGROUP GNNK17
	  PRIQTY -1
	  SECQTY -1
	DSSIZE 4 G
	BUFFERPOOL BP0
	LOCKMAX SYSTEM
	LOCKSIZE ANY;

CREATE AUXILIARY TABLE "NK"."TNK1703L"
	IN "DNNK17"."SNK1703L"
	STORES "NK"."TNK17030"
	COLUMN "RCD_TXT"
	PART 1;

CREATE UNIQUE INDEX "NK"."XNK1703X"
	ON "NK"."TNK1703L"
	USING STOGROUP GNNK17
	  PRIQTY -1
	  SECQTY -1
	BUFFERPOOL BP2     
	CLOSE NO
	PIECESIZE 4194304 K;

